trigger:
  branches:
    include:
      - master

variables:
  imageName: 'landing-page'
  acrLoginServer: 'myacrlanding.azurecr.io'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'conn-landing'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name myacrlanding
          docker build -t $(acrLoginServer)/$(imageName):$(Build.BuildId) .
          docker push $(acrLoginServer)/$(imageName):$(Build.BuildId)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'conn-landing'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group rs-group-landing --name myaks-landing --overwrite-existing

          kubectl set image deployment/landing-page \
            landing-page=$(acrLoginServer)/$(imageName):$(Build.BuildId)
